// AUTO-GENERATED by scripts/capture-rive.mjs — do not edit by hand.
// Deterministic transparent PNG frame sequences pre-rendered from the Rive
// module files (src/stories/neo/modules/riv/*.riv). Replayed by RiveClip.tsx.
export type RiveClipMeta = {
  frames: number
  fps: number
  width: number
  height: number
  /** Source timeline captured (the one that moves). */
  anim: string | null
  /** False when the module had no moving timeline (single rest frame). */
  animated: boolean
}

export const RIVE_CLIPS = {
  "hotpot": {
    "frames": 22,
    "fps": 30,
    "width": 512,
    "height": 512,
    "anim": "React",
    "animated": true
  },
  "sqlsense": {
    "frames": 21,
    "fps": 30,
    "width": 512,
    "height": 512,
    "anim": "Click",
    "animated": true
  },
  "udon": {
    "frames": 43,
    "fps": 30,
    "width": 512,
    "height": 512,
    "anim": "React",
    "animated": true
  },
  "sushimi": {
    "frames": 22,
    "fps": 30,
    "width": 512,
    "height": 512,
    "anim": "React",
    "animated": true
  },
  "docusense": {
    "frames": 20,
    "fps": 30,
    "width": 512,
    "height": 512,
    "anim": "React",
    "animated": true
  },
  "junction": {
    "frames": 31,
    "fps": 30,
    "width": 512,
    "height": 512,
    "anim": "React",
    "animated": true
  },
  "glimpse": {
    "frames": 13,
    "fps": 30,
    "width": 512,
    "height": 512,
    "anim": "React1",
    "animated": true
  },
  "foresight": {
    "frames": 22,
    "fps": 30,
    "width": 512,
    "height": 512,
    "anim": "React",
    "animated": true
  },
  "actionRunner": {
    "frames": 31,
    "fps": 30,
    "width": 512,
    "height": 512,
    "anim": "React",
    "animated": true
  },
  "actionScript": {
    "frames": 21,
    "fps": 30,
    "width": 512,
    "height": 512,
    "anim": "React",
    "animated": true
  },
  "teamwork": {
    "frames": 15,
    "fps": 30,
    "width": 512,
    "height": 512,
    "anim": "React",
    "animated": true
  },
  "feedbackLoop": {
    "frames": 15,
    "fps": 30,
    "width": 512,
    "height": 512,
    "anim": "React",
    "animated": true
  },
  "heartbeat": {
    "frames": 22,
    "fps": 30,
    "width": 512,
    "height": 512,
    "anim": "React",
    "animated": true
  },
  "smartProcess": {
    "frames": 29,
    "fps": 30,
    "width": 512,
    "height": 512,
    "anim": "Click",
    "animated": true
  },
  "forge": {
    "frames": 28,
    "fps": 30,
    "width": 512,
    "height": 512,
    "anim": "React",
    "animated": true
  },
  "skillHub": {
    "frames": 20,
    "fps": 30,
    "width": 512,
    "height": 512,
    "anim": "React",
    "animated": true
  }
} satisfies Record<string, RiveClipMeta>

export type RiveClipName = keyof typeof RIVE_CLIPS
